//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rpavy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оператор.
    /// </summary>
    // *** Start programmer edit section *** (Оператор CustomAttributes)

    // *** End programmer edit section *** (Оператор CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОператорE", new string[] {
            "ФИО as \'ФИО\'",
            "КодВхода as \'Код входа\'",
            "ID as \'ID\'"})]
    [View("ОператорL", new string[] {
            "ФИО as \'ФИО\'",
            "КодВхода as \'Код входа\'",
            "ID as \'ID\'"})]
    public class Оператор : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private int fКодВхода;
        
        private int fID;
        
        // *** Start programmer edit section *** (Оператор CustomMembers)

        // *** End programmer edit section *** (Оператор CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Оператор.ID CustomAttributes)

        // *** End programmer edit section *** (Оператор.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Оператор.ID Get start)

                // *** End programmer edit section *** (Оператор.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Оператор.ID Get end)

                // *** End programmer edit section *** (Оператор.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оператор.ID Set start)

                // *** End programmer edit section *** (Оператор.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Оператор.ID Set end)

                // *** End programmer edit section *** (Оператор.ID Set end)
            }
        }
        
        /// <summary>
        /// КодВхода.
        /// </summary>
        // *** Start programmer edit section *** (Оператор.КодВхода CustomAttributes)

        // *** End programmer edit section *** (Оператор.КодВхода CustomAttributes)
        public virtual int КодВхода
        {
            get
            {
                // *** Start programmer edit section *** (Оператор.КодВхода Get start)

                // *** End programmer edit section *** (Оператор.КодВхода Get start)
                int result = this.fКодВхода;
                // *** Start programmer edit section *** (Оператор.КодВхода Get end)

                // *** End programmer edit section *** (Оператор.КодВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оператор.КодВхода Set start)

                // *** End programmer edit section *** (Оператор.КодВхода Set start)
                this.fКодВхода = value;
                // *** Start programmer edit section *** (Оператор.КодВхода Set end)

                // *** End programmer edit section *** (Оператор.КодВхода Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Оператор.ФИО CustomAttributes)

        // *** End programmer edit section *** (Оператор.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Оператор.ФИО Get start)

                // *** End programmer edit section *** (Оператор.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Оператор.ФИО Get end)

                // *** End programmer edit section *** (Оператор.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оператор.ФИО Set start)

                // *** End programmer edit section *** (Оператор.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Оператор.ФИО Set end)

                // *** End programmer edit section *** (Оператор.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОператорE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОператорE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОператорE", typeof(IIS.Rpavy.Оператор));
                }
            }
            
            /// <summary>
            /// "ОператорL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОператорL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОператорL", typeof(IIS.Rpavy.Оператор));
                }
            }
        }
    }
}
