//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rpavy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Посадочный талон.
    /// </summary>
    // *** Start programmer edit section *** (ПосадТалон CustomAttributes)

    // *** End programmer edit section *** (ПосадТалон CustomAttributes)
    [AutoAltered()]
    [Caption("Посадочный талон")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПосадТалонE", new string[] {
            "ДатаВыд as \'Дата выдачи\'"})]
    [View("ПосадТалонL", new string[] {
            "ДатаВыд as \'Дата выдачи\'"})]
    public class ПосадТалон : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаВыд = System.DateTime.Now;
        
        private IIS.Rpavy.Пассажир fПассажир;
        
        private IIS.Rpavy.Рейс fРейс;
        
        // *** Start programmer edit section *** (ПосадТалон CustomMembers)

        // *** End programmer edit section *** (ПосадТалон CustomMembers)

        
        /// <summary>
        /// ДатаВыд.
        /// </summary>
        // *** Start programmer edit section *** (ПосадТалон.ДатаВыд CustomAttributes)

        // *** End programmer edit section *** (ПосадТалон.ДатаВыд CustomAttributes)
        public virtual System.DateTime ДатаВыд
        {
            get
            {
                // *** Start programmer edit section *** (ПосадТалон.ДатаВыд Get start)

                // *** End programmer edit section *** (ПосадТалон.ДатаВыд Get start)
                System.DateTime result = this.fДатаВыд;
                // *** Start programmer edit section *** (ПосадТалон.ДатаВыд Get end)

                // *** End programmer edit section *** (ПосадТалон.ДатаВыд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПосадТалон.ДатаВыд Set start)

                // *** End programmer edit section *** (ПосадТалон.ДатаВыд Set start)
                this.fДатаВыд = value;
                // *** Start programmer edit section *** (ПосадТалон.ДатаВыд Set end)

                // *** End programmer edit section *** (ПосадТалон.ДатаВыд Set end)
            }
        }
        
        /// <summary>
        /// Посадочный талон.
        /// </summary>
        // *** Start programmer edit section *** (ПосадТалон.Пассажир CustomAttributes)

        // *** End programmer edit section *** (ПосадТалон.Пассажир CustomAttributes)
        [PropertyStorage(new string[] {
                "Пассажир"})]
        [NotNull()]
        public virtual IIS.Rpavy.Пассажир Пассажир
        {
            get
            {
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Get start)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Get start)
                IIS.Rpavy.Пассажир result = this.fПассажир;
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Get end)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Set start)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Set start)
                this.fПассажир = value;
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Set end)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Set end)
            }
        }
        
        /// <summary>
        /// Посадочный талон.
        /// </summary>
        // *** Start programmer edit section *** (ПосадТалон.Рейс CustomAttributes)

        // *** End programmer edit section *** (ПосадТалон.Рейс CustomAttributes)
        [PropertyStorage(new string[] {
                "Рейс"})]
        [NotNull()]
        public virtual IIS.Rpavy.Рейс Рейс
        {
            get
            {
                // *** Start programmer edit section *** (ПосадТалон.Рейс Get start)

                // *** End programmer edit section *** (ПосадТалон.Рейс Get start)
                IIS.Rpavy.Рейс result = this.fРейс;
                // *** Start programmer edit section *** (ПосадТалон.Рейс Get end)

                // *** End programmer edit section *** (ПосадТалон.Рейс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПосадТалон.Рейс Set start)

                // *** End programmer edit section *** (ПосадТалон.Рейс Set start)
                this.fРейс = value;
                // *** Start programmer edit section *** (ПосадТалон.Рейс Set end)

                // *** End programmer edit section *** (ПосадТалон.Рейс Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПосадТалонE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосадТалонE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосадТалонE", typeof(IIS.Rpavy.ПосадТалон));
                }
            }
            
            /// <summary>
            /// "ПосадТалонL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосадТалонL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосадТалонL", typeof(IIS.Rpavy.ПосадТалон));
                }
            }
        }
    }
}
