//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rpavy
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проверка.
    /// </summary>
    // *** Start programmer edit section *** (Проверка CustomAttributes)

    // *** End programmer edit section *** (Проверка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроверкаE", new string[] {
            "Время as \'Время\'",
            "Дата as \'Дата\'",
            "ЗаменаЛенты as \'Замена ленты\'",
            "Оператор as \'Оператор\'",
            "Оператор.ФИО as \'ФИО\'",
            "Терминал as \'Терминал\'",
            "Терминал.Номер as \'Номер\'",
            "Оператор.ID as \'ID\'",
            "Оператор.КодВхода as \'Код входа\'"}, Hidden=new string[] {
            "Оператор.ФИО",
            "Терминал.Номер"})]
    [MasterViewDefineAttribute("ПроверкаE", "Оператор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПроверкаE", "Терминал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("ПроверкаL", new string[] {
            "Время as \'Время\'",
            "Дата as \'Дата\'",
            "ЗаменаЛенты as \'Замена ленты\'",
            "Оператор.ФИО as \'ФИО\'",
            "Терминал.Номер as \'Номер\'"})]
    public class Проверка : ICSSoft.STORMNET.DataObject
    {
        
        private string fВремя;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private string fЗаменаЛенты;
        
        private IIS.Rpavy.Оператор fОператор;
        
        private IIS.Rpavy.Терминал fТерминал;
        
        // *** Start programmer edit section *** (Проверка CustomMembers)

        // *** End programmer edit section *** (Проверка CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Проверка.Время CustomAttributes)

        // *** End programmer edit section *** (Проверка.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (Проверка.Время Get start)

                // *** End programmer edit section *** (Проверка.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (Проверка.Время Get end)

                // *** End programmer edit section *** (Проверка.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверка.Время Set start)

                // *** End programmer edit section *** (Проверка.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Проверка.Время Set end)

                // *** End programmer edit section *** (Проверка.Время Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Проверка.Дата CustomAttributes)

        // *** End programmer edit section *** (Проверка.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Проверка.Дата Get start)

                // *** End programmer edit section *** (Проверка.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Проверка.Дата Get end)

                // *** End programmer edit section *** (Проверка.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверка.Дата Set start)

                // *** End programmer edit section *** (Проверка.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Проверка.Дата Set end)

                // *** End programmer edit section *** (Проверка.Дата Set end)
            }
        }
        
        /// <summary>
        /// ЗаменаЛенты.
        /// </summary>
        // *** Start programmer edit section *** (Проверка.ЗаменаЛенты CustomAttributes)

        // *** End programmer edit section *** (Проверка.ЗаменаЛенты CustomAttributes)
        [StrLen(255)]
        public virtual string ЗаменаЛенты
        {
            get
            {
                // *** Start programmer edit section *** (Проверка.ЗаменаЛенты Get start)

                // *** End programmer edit section *** (Проверка.ЗаменаЛенты Get start)
                string result = this.fЗаменаЛенты;
                // *** Start programmer edit section *** (Проверка.ЗаменаЛенты Get end)

                // *** End programmer edit section *** (Проверка.ЗаменаЛенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверка.ЗаменаЛенты Set start)

                // *** End programmer edit section *** (Проверка.ЗаменаЛенты Set start)
                this.fЗаменаЛенты = value;
                // *** Start programmer edit section *** (Проверка.ЗаменаЛенты Set end)

                // *** End programmer edit section *** (Проверка.ЗаменаЛенты Set end)
            }
        }
        
        /// <summary>
        /// Проверка.
        /// </summary>
        // *** Start programmer edit section *** (Проверка.Оператор CustomAttributes)

        // *** End programmer edit section *** (Проверка.Оператор CustomAttributes)
        [PropertyStorage(new string[] {
                "Оператор"})]
        [NotNull()]
        public virtual IIS.Rpavy.Оператор Оператор
        {
            get
            {
                // *** Start programmer edit section *** (Проверка.Оператор Get start)

                // *** End programmer edit section *** (Проверка.Оператор Get start)
                IIS.Rpavy.Оператор result = this.fОператор;
                // *** Start programmer edit section *** (Проверка.Оператор Get end)

                // *** End programmer edit section *** (Проверка.Оператор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверка.Оператор Set start)

                // *** End programmer edit section *** (Проверка.Оператор Set start)
                this.fОператор = value;
                // *** Start programmer edit section *** (Проверка.Оператор Set end)

                // *** End programmer edit section *** (Проверка.Оператор Set end)
            }
        }
        
        /// <summary>
        /// Проверка.
        /// </summary>
        // *** Start programmer edit section *** (Проверка.Терминал CustomAttributes)

        // *** End programmer edit section *** (Проверка.Терминал CustomAttributes)
        [PropertyStorage(new string[] {
                "Терминал"})]
        [NotNull()]
        public virtual IIS.Rpavy.Терминал Терминал
        {
            get
            {
                // *** Start programmer edit section *** (Проверка.Терминал Get start)

                // *** End programmer edit section *** (Проверка.Терминал Get start)
                IIS.Rpavy.Терминал result = this.fТерминал;
                // *** Start programmer edit section *** (Проверка.Терминал Get end)

                // *** End programmer edit section *** (Проверка.Терминал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверка.Терминал Set start)

                // *** End programmer edit section *** (Проверка.Терминал Set start)
                this.fТерминал = value;
                // *** Start programmer edit section *** (Проверка.Терминал Set end)

                // *** End programmer edit section *** (Проверка.Терминал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроверкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаE", typeof(IIS.Rpavy.Проверка));
                }
            }
            
            /// <summary>
            /// "ПроверкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверкаL", typeof(IIS.Rpavy.Проверка));
                }
            }
        }
    }
}
